### ISSUE TITLE
Set group access control on upload

### ISSUE THREAD

**Issue by leondutoit** [unioslo/vscode-tsd-sync#3]
Import links have one group claim, the one intended to be used for group-based access control on upload. This should be set by adding a query parameter to the upload URL: `?group={claims.get("groups")[0]}` here https://github.com/unioslo/vscode-tsd-sync/blob/6b1e1eb0f240be5fb10a55289ac3ddb8be0a59ef/src/tsdConsts.ts#L27-L29

**Comment by f-krull** [comment]
This means the group will show up twice in the URL?

```diff
diff --git a/src/tsdConsts.ts b/src/tsdConsts.ts
index 61a15e7..59a1579 100644
--- a/src/tsdConsts.ts
+++ b/src/tsdConsts.ts
@@ -29,5 +29,5 @@ export namespace tsdConsts {
   }) =>
     `https://data.tsd.usit.no/v1/${project}/files/stream/${group}/${
       basePath ? encodeURI(basePath) : ""
-    }/${encodeURI(path)}`;
+    }/${encodeURI(path)}?group=${group}`;
 }
```

**Comment by leondutoit** [comment]
Twice indeed. It is a convention to have the group name in the path, so folder names in the import directory show the access control to users without having to inspect folder metadata.
