### ISSUE TITLE
Exclude files and folders from sync

### ISSUE THREAD

**Issue by daanknoors** [unioslo/vscode-tsd-sync#6]
I would like to be able to exclude files and folders from syncing, for example *.csv, /data, /.git. This would speed up the syncing process and allow me to keep certain files locally in the repo without them ending up on TSD.

Implementation could be similar to a .gitignore file. However, ideally it's a separate file with the same syntax (e.g. .syncignore), as I would like to have some files still on TSD but not on git and vice versa.

Thanks for the great work!

**Comment by f-krull** [comment]
Yes, good point. Currently, the .vscode folder is always ignored. Having .gitignore functionality instead would be far better.
